on: [push, pull_request]

jobs:
  run-tests-mac:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install cmake zlib boost googletest jsoncpp re2

      - name: Install Redex
        run: |
          git clone https://github.com/facebook/redex.git
          cd redex
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ../..

      - name: Install fmt
        run: |
          git clone https://github.com/fmtlib/fmt.git
          cd fmt
          git checkout 9.1.0
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ../..

      - name: Build and Test Mariana Trench
        run: |
          mkdir build
          cd build
          cmake -DREDEX_ROOT="../redex/install" -Dfmt_ROOT="../fmt/install" -DFMT_DEPRECATED_OSTREAM=ON -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          make check -j$(sysctl -n hw.ncpu)

  run-tests-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: |
          brew install cmake zlib boost jsoncpp re2 git
          brew install googletest --build-from-source
          sudo apt update
          sudo apt install default-jre default-jdk

      - name: Install fmt
        run: |
          git clone https://github.com/fmtlib/fmt.git
          cd fmt
          git checkout 9.1.0
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          cd ../..


      - name: Install Redex and build and test Mariana Trench
        run: |
          export CMAKE_PREFIX_PATH=/home/linuxbrew/.linuxbrew/opt/jsoncpp:/home/linuxbrew/.linuxbrew/opt/zlib
          git clone https://github.com/facebook/redex.git
          cd redex
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          cd ../..
          mkdir build
          cd build
          cmake -DREDEX_ROOT="../redex/install" -Dfmt_ROOT="../fmt/install" -DFMT_DEPRECATED_OSTREAM=ON -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          make check -j$(nproc)
