on: [push, pull_request]

jobs:
  run-tests-mac:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install --formula cmake zlib boost googletest jsoncpp re2

      - name: Install Redex
        run: |
          git clone https://github.com/facebook/redex.git
          cd redex
          mkdir build
          cd build
          cmake -DZLIB_HOME="$(brew --prefix)/opt/zlib" -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ../..

      - name: Install fmt
        run: |
          git clone https://github.com/fmtlib/fmt.git
          cd fmt
          git checkout 9.1.0
          mkdir build
          cd build
          cmake -DCMAKE_CXX_STANDARD=17 -DFMT_TEST=OFF -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ../..

      - name: Build and Test Mariana Trench
        run: |
          mkdir build
          cd build
          cmake -DREDEX_ROOT="$PWD/../redex/install" -Dfmt_ROOT="$PWD/../fmt/install" -DFMT_DEPRECATED_OSTREAM=ON -DEXCLUDE_INTEGRATION_TESTS="check_cast_types" -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          make check -j$(sysctl -n hw.ncpu)

  run-tests-linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: |
          brew install --formula cmake zlib boost googletest jsoncpp re2 git
          sudo apt update
          sudo apt install default-jre default-jdk

      - name: Install fmt
        run: |
          git clone https://github.com/fmtlib/fmt.git
          cd fmt
          git checkout 9.1.0
          mkdir build
          cd build
          cmake -DCMAKE_CXX_STANDARD=17 -DFMT_TEST=OFF -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          cd ../..


      - name: Install Redex and build and test Mariana Trench
        run: |
          export CMAKE_PREFIX_PATH=/home/linuxbrew/.linuxbrew/opt/jsoncpp:/home/linuxbrew/.linuxbrew/opt/zlib
          git clone https://github.com/facebook/redex.git
          cd redex
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          cd ../..
          mkdir build
          cd build
          cmake -DREDEX_ROOT="$PWD/../redex/install" -Dfmt_ROOT="$PWD/../fmt/install" -DFMT_DEPRECATED_OSTREAM=ON -DEXCLUDE_INTEGRATION_TESTS="check_cast_types" -DCMAKE_INSTALL_PREFIX="../install" ..
          make -j$(nproc)
          make install
          make check -j$(nproc)
